name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Docker Registry
        run: echo "${{ secrets.DIGITALOCEAN_API_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      - name: Build and Push with docker-compose
        run: |
          docker compose down -v
          docker compose up -d --build
          docker tag linktic-front registry.digitalocean.com/linktic-registry/linktic-front:latest
          docker push registry.digitalocean.com/linktic-registry/linktic-front:latest

      - name: Deploy to DigitalOcean
        run: |
          echo "Deploy step here"